[[SpFFT]]
arch = "aarch64"
git-tree-sha1 = "97a8ed383e32ab0bd7e5fb62be189453fccce37e"
lazy = true
mpi = "mpich"
os = "macos"

    [[SpFFT.download]]
    sha256 = "7d006434339bcc099a7c47619c0aed64ab080922d764efe5bec7bb9d182b7f42"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[SpFFT]]
arch = "aarch64"
git-tree-sha1 = "87516fc2acdae609dff55e53482cb30baca5de5e"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[SpFFT.download]]
    sha256 = "cbcd4444f4b1bde874e60c50112bf273fbf8ce1caf44f0273d0c138f2e7a703b"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[SpFFT]]
arch = "aarch64"
git-tree-sha1 = "6685a4191235f0f087b3c3e30974297fac16b73d"
lazy = true
mpi = "openmpi"
os = "macos"

    [[SpFFT.download]]
    sha256 = "a05b1fef09291a97e1a4882ec8ff5118a81d5a1cec14e3c4dcb500f5a0a645b5"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[SpFFT]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f75d428c30e88c61c1b5d257142f6fd847681a8a"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[SpFFT.download]]
    sha256 = "8055685fb02dd10e4e3b3ce44cf8b852f32b04ece569e174bacf05e7968f48c7"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.aarch64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[SpFFT]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "039246623bd71a999176b63d6c017978d06fb256"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[SpFFT.download]]
    sha256 = "a02274a5f71e82e845ea375db88f95ab30f1962d231eb12613dd95347d91ba1d"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.aarch64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[SpFFT]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d81c9dd9433b0beed0ebf53830f4bedae3b43212"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[SpFFT.download]]
    sha256 = "b6bffa695879f1249b5ac035a2bc81c967b37c432a9b6404bedb77ac55116459"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.aarch64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[SpFFT]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8dc1849d64c319ecf9b5447aac8c3e3843c71fb4"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[SpFFT.download]]
    sha256 = "a70fc2e487386fe3f5299174de56551303d640340dcf41550ab2b59a3b158d04"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.aarch64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[SpFFT]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b88f2b5703f2cb6ddedcf2bb3d40c832bcafec1"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[SpFFT.download]]
    sha256 = "15d8682cf81bf4bc4c57a9aa1f249ef7ef17ea4831275f5b72b82dc0f0c9627b"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.aarch64-linux-musl-cxx11-mpi+openmpi.tar.gz"
[[SpFFT]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7544f8463798dacaa20ee090f371b1e8b6b6bba6"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[SpFFT.download]]
    sha256 = "dbbee9cbd37da4e422c14c93d751efb65fabf0455a4a0751a731518767335acd"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.armv6l-linux-gnueabihf-cxx11-mpi+mpich.tar.gz"
[[SpFFT]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1b30a4e12ba893461d16368bc602d1b100cc207a"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[SpFFT.download]]
    sha256 = "6a5644541eba1e7fdc62101197951061cbe2bd584e1cd2dcb57ebfb78a319795"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.armv6l-linux-gnueabihf-cxx11-mpi+mpitrampoline.tar.gz"
[[SpFFT]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d7b8862d587e44b30b152f5c1515d3b4af7beba"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[SpFFT.download]]
    sha256 = "5ad79a9832eed489aab42fa6e8019623c63157bb543d16936d4d085cb4aa74de"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.armv6l-linux-musleabihf-cxx11-mpi+mpich.tar.gz"
[[SpFFT]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f01424a827e7cdc2c2bac885afdd1ea444430589"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[SpFFT.download]]
    sha256 = "208f3d11345c1d1da5139eed2b7cac58595c7234adf4952516f87fbe6fdb048d"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.armv6l-linux-musleabihf-cxx11-mpi+openmpi.tar.gz"
[[SpFFT]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19b7b76775fa6fea772003a46305b4031ad45c91"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[SpFFT.download]]
    sha256 = "c11dace54fc702214712b49eb5ebbece392ff3d65290319de16492bcf916cf57"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.armv7l-linux-gnueabihf-cxx11-mpi+mpich.tar.gz"
[[SpFFT]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7c67b7277a8d7e01878060b07e8da63d2909046"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[SpFFT.download]]
    sha256 = "8a7e68122fd2a2f69f0b6db7ce1bf73ffa997178d5191fb1866587340473eb3f"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.armv7l-linux-gnueabihf-cxx11-mpi+mpitrampoline.tar.gz"
[[SpFFT]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d0b6ffde017e1c9170aa8f6b4a54e99541339627"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[SpFFT.download]]
    sha256 = "abc714a5fdfe41b320b6141a45f1c467d14afc6ddb6a62d04bd4c607f045027d"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.armv7l-linux-gnueabihf-cxx11-mpi+openmpi.tar.gz"
[[SpFFT]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e5fbf0fbe7fd7497c4288b987015c47482092a7"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[SpFFT.download]]
    sha256 = "7d52076346ca3f756297895bcb317752fdfa40d9b1a0d03d37d269610bbc9e40"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.armv7l-linux-musleabihf-cxx11-mpi+mpich.tar.gz"
[[SpFFT]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ff742bb7fdbcba2ce2b2040055759a8b972aa10"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[SpFFT.download]]
    sha256 = "fe3b277bf88f600b57a7d61c956e70389bcd013529ec415b22df8f7ce5443a1c"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.armv7l-linux-musleabihf-cxx11-mpi+openmpi.tar.gz"
[[SpFFT]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16d8ebd2e1daeaeb9bbc88293da95ca9c43d5a1f"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[SpFFT.download]]
    sha256 = "9d1dff7dec082bd75e108778d7b63c3636734998d0fd8062b30171d2aba22ea0"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.i686-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[SpFFT]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ea1c6ad177bea17181e576c616bfa454b19a0b0"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[SpFFT.download]]
    sha256 = "3802e31156a799e0cb56d5ea22081dd2517e6ec7cef1ba20911a722f3e734bc8"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.i686-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[SpFFT]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "356d275c128835cd579cd015449aa5889d1b4865"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[SpFFT.download]]
    sha256 = "e417a0119440649ebd241dcd15cbb11d6d4840284367902d6512a495c702f2e5"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.i686-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[SpFFT]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9b8b8b1681fd1b2b7fb53d895fa1452eab57444"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[SpFFT.download]]
    sha256 = "6e787643f8ceea0b7b48821bc3029789c27a183a06055a7d3534cb682bbce78a"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.i686-linux-musl-cxx11-mpi+mpich.tar.gz"
[[SpFFT]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c2e29fd7f5880723eff11ecf495b7b42a043daa3"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[SpFFT.download]]
    sha256 = "a1b8ebb422c0fa2b4998e938158fa110b4f9ec6857146b0ba1a7e9f1c52a880a"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.i686-linux-musl-cxx11-mpi+openmpi.tar.gz"
[[SpFFT]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45f52ef011911e8e7391ee495c3bfe93cfb0177f"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[SpFFT.download]]
    sha256 = "79873618ab6f14322ff84c4de2cf2a90f64c6ca2bd6ea7da8afa99c2d075acbf"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.powerpc64le-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[SpFFT]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6fbdf9ad8e42b77c0c41c2bde70107673776fed0"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[SpFFT.download]]
    sha256 = "bf21a3ea4efee2f5317dd6a290d71077d46e46936563f1d5e224621a79ae9bc7"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.powerpc64le-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[SpFFT]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "274e2accea899844e56dac72bf059f7d3f10ec33"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[SpFFT.download]]
    sha256 = "f7962ed7a673f3f119540715f7d854c0026875562b1edf31082ba2430e812f61"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.powerpc64le-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[SpFFT]]
arch = "x86_64"
git-tree-sha1 = "b98d44b429d5b17c597eecd6673fe475e404cd6c"
lazy = true
mpi = "mpich"
os = "macos"

    [[SpFFT.download]]
    sha256 = "899d3bdb2843f2dc8c7540f60cae18c5b177c4b033e5b9073d6abc25eabd1298"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[SpFFT]]
arch = "x86_64"
git-tree-sha1 = "f17af8cb2a750f48df5238b2cfe3caacdbddbed5"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[SpFFT.download]]
    sha256 = "f9f75a6e0d89cc0e0923745842ca25e6bb26a22f8e9d1163faaf339880718b49"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[SpFFT]]
arch = "x86_64"
git-tree-sha1 = "bce0d9ca1d0e35705d4bd67ddffbaf826bfc1a6f"
lazy = true
mpi = "openmpi"
os = "macos"

    [[SpFFT.download]]
    sha256 = "0791ec83f2d5fa7bacb0863bcda4db1c9a9cca0bf14eef1ac8e00db3d1051c11"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[SpFFT]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d331ddac806b658711daa8af0460e55c83834fc1"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[SpFFT.download]]
    sha256 = "399dbb219d2ddc6d1c697456130351eba288e15d38b13f52c8ea0c01c9b9279f"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.x86_64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[SpFFT]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff7df1e589304e8bd950bbc7c5f1a3deab430413"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[SpFFT.download]]
    sha256 = "0ee538f4f72bae4ae22ee4bf25f37b897ca35cf63bc9a3f71a89f14ee68080a5"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.x86_64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[SpFFT]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "122a006fd2f00c6d0f11be2124303296052f86e4"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[SpFFT.download]]
    sha256 = "43cd90c93cd2fdfd0052dbf3060a1399914b10f268e905f5db785de8b5b88b1f"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.x86_64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[SpFFT]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6fd79bbb9fd16e7d423330fecb12c7fdae094d6"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[SpFFT.download]]
    sha256 = "8febdb87cf7c949bb80f83999d3a75e8a67e6f58764bb957dd414580d9282d36"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.x86_64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[SpFFT]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9179154a476a89079a48f0e06a95bdbcad75de41"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[SpFFT.download]]
    sha256 = "385c61ffd261a081f13b1f1421d72874f199622709468835fdf4a73c7eb17021"
    url = "https://github.com/JuliaBinaryWrappers/SpFFT_jll.jl/releases/download/SpFFT-v1.1.1+0/SpFFT.v1.1.1.x86_64-linux-musl-cxx11-mpi+openmpi.tar.gz"
